games/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.messages.context_processors import messages
from games.views import show_games, choose_game, game_finished, show_counting_game, search_games
from messages.views import show_messages, compose_message, show_message
from users.forms import ParentRegistrationForm
from users.views import registration
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    # Examples:'
    url(r'^$', show_games, name='show_games'),
    url(r'^search/$', search_games, name='search_games'),

    url(r'^finished/(?P<id>[\d]+)/$', game_finished, name='game_finished'),

    url(r'^game/(?P<id>[\d]+)/$', choose_game, name='choose_game'),
    url(r'^game/(?P<id>[\d]+)/(?P<game_id>[\d]+)/(?P<image_id>[\d]+)/(?P<game_round>[\d]+)/$', choose_game, name='choose_game'),

    url(r'^game/counting/(?P<id>[\d]+)/$', show_counting_game, name='show_counting_game'),
    url(r'^game/counting/(?P<id>[\d]+)/(?P<game_id>[\d]+)/(?P<game_round>[\d]+)/$', show_counting_game, name='show_counting_game'),

    # url(r'^compose/$', compose_message, name='compose_message'),
    # url(r'^message/(?P<id>[\d]+)/$', show_message, name='show_message'),



)

mais/urls.py
import os
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from mais.settings import MEDIA_ROOT
from users.views import home

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^users/', include('users.urls')),
    url(r'^messages/', include('messages.urls')),
    url(r'^materials/', include('materials.urls')),

    url(r'^games/', include('games.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^admin_media/(.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'admin_media')}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': os.path.join(os.path.dirname(__file__), 'static')}),
)

games/models.py
from django.db import models
from users.models import BaseUser

from taggit.managers import TaggableManager

LEVEL_CHOICES = (
    ("easy", "Easy"),
    ("medium", "Medium"),
    ("hard", "Hard"),
)
# Create your models here.
class ImageCategory(models.Model):
    name = models.CharField(verbose_name="Name", max_length=250)
    tags = TaggableManager()

    class Meta:
        verbose_name = "Image category"
        verbose_name_plural = "Images categories"

    def __unicode__(self):
        return self.name

class BaseGame(models.Model):
    name = models.CharField(verbose_name="Name", max_length=250)
    description = models.TextField(verbose_name="Description", null=True, blank=True)
    level = models.CharField(verbose_name="Level", choices=LEVEL_CHOICES, max_length=50 )
    rounds = models.IntegerField(verbose_name="Rounds", default=3)
    tags = TaggableManager()

    class Meta:
        verbose_name = "Base game"
        verbose_name_plural = "Bases games"


    def __unicode__(self):
        return self.name

    def get_counting_instance(self):
        try:
            counting = CountingGame.objects.get(id=self.id)
        except:
            counting = None
        return counting

    def is_counting_game(self):
        if self.get_counting_instance():
            return True
        else:
            return False


class GameRecognition(BaseGame):
    category_of_images = models.ForeignKey(ImageCategory, verbose_name="Image category", help_text="Random images from this category")
    images_per_round = models.IntegerField(verbose_name="Images per round", default=3)

    class Meta:
        verbose_name = "Game recognition setting"
        verbose_name_plural = "Games recognitions settings"

class CountingGame(BaseGame):
    max_number = models.IntegerField(verbose_name="Max randomed number")
    allowed_symbols = models.CharField(verbose_name="Allowed symbols", default="*,/,+,-", max_length=20)

    class Meta:
        verbose_name = "Counting game"
        verbose_name_plural = "Counting games"


class RecognitionImage(models.Model):
    image = models.ImageField(verbose_name="Image", upload_to="media/game_images/")
    name = models.CharField(verbose_name="Name", max_length=250)
    category = models.ForeignKey(ImageCategory, verbose_name="Image category")

    class Meta:
        verbose_name = "Recognition image"
        verbose_name_plural = "Recognitions images"

    def __unicode__(self):
        return self.name

class GameAnswer(models.Model):
    game = models.ForeignKey(BaseGame, verbose_name="Game")
    player = models.ForeignKey(BaseUser, verbose_name="Player")
    points = models.IntegerField(verbose_name="Points", default=0)
    randomed_images = models.ManyToManyField(RecognitionImage, null=True,blank=True)

    class Meta:
        verbose_name = "Game answer"
        verbose_name = "Games answers"

    def __unicode__(self):
        return "%s Points: %s" % (self.player, self.points)

games/forms.py
import random
import string
from django import forms
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _
from games.models import LEVEL_CHOICES
from users.models import BaseUser, Teacher, Parent


class GameRecognitionForm(forms.Form):
    answer = forms.ChoiceField(label="Answer", required=False)

    def __init__(self, *args, **kwargs):
        self.image = kwargs.pop("image")
        self.choices= kwargs.pop("choices",None)
        self.answer= kwargs.pop("answer",None)

        super(GameRecognitionForm, self).__init__(*args, **kwargs)
        choices = []
        if self.choices:
            for choice in self.choices:
                choices.append( (choice,choice) )
            self.fields['answer'].widget = forms.RadioSelect(choices=choices)

            #self.fields['answer'].choices = choices
        #self.fields['date_from'].widget = forms.SplitDateTimeField

    # def clean(self):
    #     cleaned_data = self.cleaned_data
    #     return cleaned_data

    def is_correct(self):
        if self.answer == self.image.name:
            return True
        else:
            return False

games/views.py
import random
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from games.forms import GameRecognitionForm
from games.models import GameRecognition, RecognitionImage, GameAnswer, CountingGame, BaseGame


@login_required
def show_games(request):
    template = "games/show_all_games.html"
    games = BaseGame.objects.all()

    data = {'games': games}
    return render_to_response(template, data, context_instance=RequestContext(request))

@login_required
def search_games(request):
    template = "games/show_all_games.html"
    search = request.POST.get('search',None)
    print search
    games = BaseGame.objects.filter((Q(name=search) | Q(description=search)))

    data = {'games': games}
    return render_to_response(template, data, context_instance=RequestContext(request))

@login_required
def show_counting_game(request, id=None, game_id=None, game_round = None ):
    template = "games/game_counting.html"
    game = CountingGame.objects.get(id=id)
    if not game_id:
        player_game = GameAnswer.objects.create(game=game, player=request.user)
    else:
        player_game = GameAnswer.objects.get(id=game_id)

    if not game_round:
        game_round = 1
    else:
        game_round = int(game_round) + 1

    if request.POST:
        answer = request.POST.get('answer',None)
        text_answer = request.POST.get('text_answer',None)
        print answer,text_answer,  answer == text_answer
        if answer == text_answer:
            player_game.points = player_game.points + 1
            player_game.save()
        else:
            player_game.points = player_game.points - 1
            player_game.save()

    if(game_round > game.rounds):
        return redirect( reverse("game_finished",args=[player_game.id]))


    sign = random.choice( game.allowed_symbols.split(',') )
    number1 = random.randint(0, game.max_number)
    number2 = random.randint(0, game.max_number)
    answer = 0
    if sign == "+":
        answer = number1 + number2
    elif sign == "-":
        answer = number1 - number2
    elif sign == "*":
        answer = number1 * number2
    elif sign == "/":
        number1 = number1 * number2
        answer = number1 / number2

    formula = "%s %s %s = ?" % (number1,sign,number2)


    data = {'game': game,'player_game':player_game, 'game_round':game_round, 'answer':answer,'formula':formula}
    return render_to_response(template, data, context_instance=RequestContext(request))


@login_required
def choose_game(request, id=None, game_id=None, image_id=None, game_round = None):
    template = "games/game.html"
    game = GameRecognition.objects.get(id=id)
    if not game_id:
        player_game = GameAnswer.objects.create(game=game, player=request.user)
    else:
        player_game = GameAnswer.objects.get(id=game_id)

    if not game_round:
        game_round = 1
    else:
        game_round = int(game_round) + 1


    if request.POST:
        answer_image = RecognitionImage.objects.get(id=image_id)
        player_game.randomed_images.add(answer_image)
        player_game.save()
        answer = request.POST.get('answer',None)
        last_form = GameRecognitionForm(request.POST,image=answer_image,answer=answer)
        last_form.is_valid()
        if last_form.is_correct():
            player_game.points = player_game.points + 1
            player_game.save()
        else:
            player_game.points = player_game.points - 1
            player_game.save()

    if(game_round > game.rounds):
        return redirect( reverse("game_finished",args=[player_game.id]))

    randomed_images = player_game.randomed_images.all().values_list('id',flat=True)
    randomed_images = list(randomed_images)
    if image_id:
        randomed_images.append(image_id)

    if randomed_images:
        image = RecognitionImage.objects.filter(category=game.category_of_images).exclude(id__in=randomed_images).order_by('?')[0]
    else:
        image = RecognitionImage.objects.filter(category=game.category_of_images).order_by('?')[0]

    answers = RecognitionImage.objects.filter(category=game.category_of_images).exclude(id=image.id).order_by('?')
    answers = answers[:game.images_per_round-1].values_list('name',flat=True)
    answers = list(answers) + [image.name,]
    form = GameRecognitionForm(image=image,choices=sorted(answers))




    data = {'game': game,'image':image,'form':form,'player_game':player_game, 'game_round':game_round}
    return render_to_response(template, data, context_instance=RequestContext(request))

def game_finished(request,id):
    template = "games/game_finished.html"
    player_game = GameAnswer.objects.get(id=id)
    game = player_game.game
    data = {'game': game, 'player_game':player_game}
    return render_to_response(template, data, context_instance=RequestContext(request))

templates/games/game.html
{% extends "base.html" %}

{# if you want url of this template then use {% url show_messages %}  #}

{% block menu %}
    {% include "games/games_menu.html" %}
    {#  we include message menu to keep statment of DRY (Dont repat yourself)  #}
{% endblock %}

{% block content %}

    {# We check if any messages exists #}


    <div id="GAME">

        <img src="{{ image.image.url }}">
        {% if game.id and player_game.id and image.id and game_round %}
            <form method="post" action="{% url "choose_game" game.id player_game.id image.id game_round %}">
        {% else %}
            <form method="post">
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
        </form>

    </div>

{% endblock %}	
	

templates/games/game_counting.html
{% extends "base.html" %}

{# if you want url of this template then use {% url show_messages %}  #}

{% block menu %}
    {% include "games/games_menu.html" %}
    {#  we include message menu to keep statment of DRY (Dont repat yourself)  #}
{% endblock %}

{% block content %}

    {# We check if any messages exists #}


    <div id="GAME">
        <h1>{{ formula }}</h1>
        {% if game.id and player_game.id and game_round %}
            <form method="post" action="{% url "show_counting_game" game.id player_game.id game_round %}">
        {% else %}
            <form method="post">
        {% endif %}
        {% csrf_token %}
        <input type="hidden" name="answer" id="answer" value="{{ answer }}" />
        <input type="text" name="text_answer" id="text_answer" />
        <input type="submit" value="Submit">
        </form>

    </div>

{% endblock %}	
	

templates/games/game_finished.html
{% extends "base.html" %}

{# if you want url of this template then use {% url show_messages %}  #}

{% block menu %}
    {% include "games/games_menu.html" %}
    {#  we include message menu to keep statment of DRY (Dont repat yourself)  #}
{% endblock %}

{% block content %}

    {# We check if any messages exists #}


    <div id="GAME">
    Game: {{ game.name }}, rounds {{ game.rounds }}, level {{ game.level }} <br />
    SCORE: {{ player_game.points }}

    </div>

{% endblock %}	
	

templates/games/games_menu.html
<li><a href="{% url "show_games" %}">Games</a></li>

templates/games/show_all_games.html
{% extends "base.html" %}

{# if you want url of this template then use {% url show_messages %}  #}

{% block menu %}
    {% include "games/games_menu.html" %}
    {#  we include message menu to keep statment of DRY (Dont repat yourself)  #}
{% endblock %}

{% block content %}
    <div id="GAMES">

	<p>Available games:</p>

	<P style="margin-top: 20px">
		<table id="gamesTable">
			<thead style="border-bottom-style: outset">
				<th id="gamesTh"> Game: </th>
				<th id="gamesTh"> Level </th>
				<th id="gamesTh"> Rounds </th>
				<th id="gamesTh"> Description </th>
			</thead>
			
			{# We check if any messages exists #}
    		{% if games %}

        	{% for game in games %}
	
			<tr class="game">
				<td id="gamesTd" class="name">
					{% if game.is_counting_game %}
	                	<a href="{% url "show_counting_game" game.id %}"> {{ game.name }}</a>
		            {% else %}
		                <a href="{% url "choose_game" game.id %}"> {{ game.name }}</a>
		            {% endif %}
				</td>
				<td id="gamesTd" class="level">
					{{ game.get_level_display }}
				</td>
				<td id="gamesTd" class="rounds">
					{{ game.rounds }} 
				</td>
				<td id="gamesTd" class="description">
					{{ game.description }}
				</td>
			</tr>
			{% endfor %}
		    {% else %}
		        Go play outside
		    {% endif %}
		</table>
	</P>
	</div>

{% endblock %}	
	